# Generated by Django 5.2.7 on 2025-10-13 14:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 10, 13, 14, 4, 32, 67900, tzinfo=datetime.timezone.utc))),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2025, 10, 13, 14, 19, 32, 67900, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
