# Generated by Django 5.2.7 on 2025-10-23 13:47

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_forgotpasswordtoken_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='expired_at',
            field=models.DateTimeField(default=account.models.get_expiry_time),
        ),
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='token',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
