# Generated by Django 5.2.7 on 2025-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
